---
title: "Non-Fiction Writing"
description: This is a collection of highlights from my analytical writing - both from class and extracurricular activities. See the essays ore articles sections for further information.
format: html
---
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/2webt5TTKJiCuxd2khD2JA?utm_source=generator&theme=0" width="100%" height="100" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>


## Essays and Classwork

*Each essay has been linked with a short description of it's topic and a general date that it was written. Each of them are research papers generally centering around themes of law, media, politics, and digital worlds.*

<br><br>
[AI, Music, and the Evolution of IP Frameworks (In Progress)](https://www.instagram.com/claremontjlpp/?hl=en){.btn .btn-danger .btn-sm} 

This is an essay investigating the legal implications of AI in the Entertainment Industry. I follow the development of Intellectual Property and Entertainment Law, using key cases regarding music sampling to argue for conscientious use of AI, especially in content creation, and highlight emerging blind spots in media regulation. This is actively being written, and has been in progress for a few months. Click the link above to see more from the Claremont Journal of law and Public Policy.

Writing for: Claremont Journal of Law and Public Policy

Started In: Fall 2024

[Prejudicial Posthumanism: A Racialized Reframing of Artificial Life Narratives](https://drive.google.com/file/d/1fT7zhOf9CH2nU6f8SnbkJ9_DfPmWZemg/view?usp=drive_link){.btn .btn-success .btn-sm}
 
This essay explores the intersection of posthumanism, AI, and societal biases, particularly in Western culture. It argues that narratives surrounding artificial life, from ancient myths to modern science fiction, reflect and perpetuate deeply ingrained prejudices. As AI develops, these biases may be amplified, shaping how we understand and interact with AI technologies. The essay critically examines how films like Blade Runner and Ex Machina mirror fears of subjugation, servitude, and racial oppression, projecting these anxieties onto AI. It emphasizes the need to reconsider AI narratives to avoid replicating historical injustices, calling for a future where AI promotes ethical coexistence and mutual growth.

Written in: Spring 2024

For: Cinema and AI - Pomona College

*^Also published in [The Loop](https://jazzminpearlduncan.github.io/Website-Project/TheLoop.html)*

[The Internet: A Reframing of the Bridge Between the Real and the Fake](https://drive.google.com/file/d/1_iD7_O4GCbyMWFvxQa818CSkZ9ekhAhP/view?usp=drive_link){.btn .btn-warning .btn-sm} 

This essay explores how social media bridges digital and physical activism, countering claims that it fosters only passive engagement. It examines the role of weak and strong ties in activism, the free-rider problem in movements, and how decentralized digital organizing mobilizes resources and drives collective action. It also highlights how online activism legitimizes movements and mirrors historical grassroots efforts. Ultimately, the essay reframes social media as a powerful tool for political organizing with real-world impact.

Written in: Fall 2023

For: Political Dialogue and Resistance - Pomona College

## Articles and Journalism

*My work as a journalist has centered around community engagement through education and documentation. I am incredibly passionate about platforming, explaining, or organizing ideas related to culture in various formats with an investigative, journalistic mindset.*

### The Feedbacker (Founding Editor & Writer - Current)
*The Feedbacker is the only music publication in Claremont; started by a group of editors, including myself. I pitch, write, and revise articles along with a rotating team of writers -- each artilce is published to [our website](https://feedbacker.blog/) using WordPress. I specialize in local artist news and music history reporting. Many of my articles have not been published yet since my work has largely been centered around editing/managing other writers; but you can browse the current website at feedbacker.blog. I have multiple student/local LA new artist profiles/interviews and opinion pieces in the works, so be on the lookout for those in the coming weeks!*

### The Knight Times Newspaper (Staff Writer & Opinions Editor 2019-2022)
*For my high school's newspaper, I wrote and edited articles (largely centered around pop culture, politics, and local events), and designed pages for each month's distribution. Below are links to the digital copies of a few of our papers; you can see a couple of articles I wrote and pages I designed during my senior year, or flip through the rest of the paper*

[Jan 2022 Issue](https://issuu.com/ehshouston/docs/issue_6_combined){.btn .btn-success .btn-sm}
 [Sep 2021 Issue](https://issuu.com/ehshouston/docs/issue_2_combined?fr=sNzMwZjQ1MDA5NTg){.btn .btn-success .btn-sm}
 [Aug 2021 Issue](https://issuu.com/ehshouston/docs/august_2021_issue_1?fr=sOWFjMTQ1MDA5NTg){.btn .btn-success .btn-sm}

### The Post Newspaper of Galveston County (Guest Writer 2021)
*Below are links to the articles I wrote as a Guest at the Post Newspaper of Galveston County, with the guidance of an editor.*

[Ill Communication: Generations Speak Out on Being Heard](https://thepostnewspaper.net/2021/08/03/ill-communication-generations-speak-out-on-being-heard/){.btn .btn-success .btn-sm}
[Life, Altered: Covid & its impact on teenagers](https://thepostnewspaper.net/2021/03/23/life-altered-covid-its-impact-on-teenagers/){.btn .btn-success .btn-sm}

## Honorable Mentions

### [CCTV Revival](https://www.youtube.com/user/ClaremontCollegesTV){.btn .btn-dark .btn-sm}

CCTV is an inactive broadcast journalism organization on campus at the 5C's. I am currently working to revive the organization and broaden its scope as an on-campus video production hub. The link is to their YouTube channel; a newer version is coming soon (likely in the Fall)!

### [Halloweekend in Claremont](https://jazzminpearlduncan.github.io/Website-Project/Halloweekend.html){.btn .btn-dark .btn-sm}

This is a short documentary that I made in Fall 2024 as a class project that covered the party promotion culture at the 5C's, particularly thoughout Halloween weekend. It features interviews from students and alumni, academic analysis, and general coverage regarding the party culture(s) in Claremont.

### [Tech Accountability Archive (TAA)](https://jazzminpearlduncan.github.io/Website-Project/TAA.html){.btn .btn-dark .btn-sm}

This is another class project from Fall 2024. This project focused on documenting information about major tech companies, and creating a centralized archive containing vital information -- including Labor Practices, Data Ethics, and more.