project:
  type: website
  output-dir: docs
  
website:
  title: "- jazz :)"
  navbar:
    right:
      - text: "(!about me!)"
        href: about.qmd
           
      - text: "mutli-media projects"
        menu:
         - text: "arbistrology generator"
           href: multi/Arbistrology.qmd
         - text: "hi-de-ho animation"
           href: multi/Hi-De-Ho.qmd
         - text: "the loop zine"
           href: multi/TheLoop.qmd
         - text: "halloweekend in claremont documentary"
           href: multi/Halloweekend.qmd
         - text: "music (under construction)"

           
      - text: "writing and photography"
        menu:
          - text: "journalism & non-fiction"
            href: nonfiction.qmd
          - text: "poetry & creative writing (under construction)"
          - text: "photography (under construction)"

      - text: "data viz"
        menu:
          - text: "project 1 - part 1"
            href: dataviz/Project1-1.qmd
          - text: "project 1 - part 2"
            href: dataviz/Project1-2.qmd
          - text: "project 2"
            href: dataviz/Project2.qmd
          - text: "project 3"
            href: dataviz/Project3.qmd
          - text: "project 4"
            href: dataviz/Project4.qmd
            
      - text: "contact me!"
        href: contact.qmd
        
    
  page-footer: 
    left: "Jazzmin (jazz) Pearl Duncan"

format:
  html:
    css: styles.css
    toc: true
    page-layout: full


