project:
  type: website
  output-dir: docs
  
website:
  title: "best, jazz"
  navbar:
    left:
      - href: about.qmd
        text: "about me"
      - href: resume.qmd
        text: "resumé"
    right:
      - text: "projects"
        menu:
         - text: "The Loop"
           href: TheLoop.qmd
         - text: "Hi-De-Ho: Honoring Cab Calloway through Animation"
           href: Hi-De-Ho.qmd
         - text: "Halloweekend in Claremont"
         - text: "Cowboy Poker"
         - text: "Tech Accountability Archive"

           
      - text: "writing"
        menu:
          - text: "poems & creative writing"
          - text: "essays"
          - text: "organizations"
format:
  html:
    theme:
      - cerulean
    css: styles.css
    toc: true
    page-layout: full


