project:
  type: website
  output-dir: docs
  
website:
  title: "- jazz :)"
  navbar:
    right:
      - text: "(!about me!)"
        href: about.qmd
           
      - text: "projects"
        menu:
         - text: "Hi-De-Ho (Media History Edit)"
           href: Hi-De-Ho.qmd
         - text: "The Loop (Publishing)"
           href: TheLoop.qmd
         - text: "Halloweekend in Claremont (Documentary)"
           href: Halloweekend.qmd
         - text: "Tech Accountability Archive (Abandoned)"
           href: TAA.qmd
           
      - text: "other works"
        menu:
          - text: "Non-Fiction Writing"
            href: nonfiction.qmd
          - text: "poems & creative writing (under construction)"
          - text: "photography (under construction)"
          - text: "music (under construction)"

      - text: "Data Viz"
        menu:
          - text: "Proejct 1 - Part 1"
            href: Project1-1.qmd
          - text: "Project 1 - Part 2"
            href: Project1-2.qmd
          - text: "Proejct 2"
            href: Project2.qmd
          - text: "Project 3"
            href: Project3.qmd
          - text: "Project 4"
            href: Project4.qmd
            
      - text: "contact me!"
        href: contact.qmd
        
    
  page-footer: 
    left: "Jazzmin (jazz) Pearl Duncan"

format:
  html:
    css: styles.css
    toc: true
    page-layout: full


