project:
  type: website
  output-dir: docs
  
website:
  title: "- Jazzmin Duncan <3"
  navbar:
    right:
      - text: "About Me"
        href: basics/about.qmd
           
      - text: "Multi-Media Projects"
        menu:
         - text: "Halloweekend in Claremont Documentary"
           href: multi/Halloweekend.qmd
         - text: "The Loop Zine"
           href: TheLoop.qmd
         - text: "Hi-De-Ho Animation"
           href: multi/Hi-De-Ho.qmd
         - text: "Space Travel Benefits Portal"
           href: multi/astro/Arbistrology.qmd
         - text: "Music (under construction)"

           
      - text: "Writing and Photography"
        menu:
          - text: "Essays & Articles"
            href: writing/nonfiction.qmd
          - text: "Poetry & Creative Writing"
            href: writing/poetry.qmd
          - text: "Photography (under construction)"
      



            
      - text: "Contact"
        href: basics/contact.qmd
        
    
  page-footer: 
    left: "Jazzmin (Jazz) Pearl Duncan"

format:
  html:
    css: styles.css
    toc: true
    page-layout: full


