project:
  type: website
  output-dir: docs
  
website:
  title: "Jazzmin Duncan"
  navbar:
    left:
      - href: index.qmd
        text: "Landing Page"
    right:
      - text: "More About Me"
        href: about.qmd
      - text: "Data Viz"
        menu:
         - text: "set 1"
           href: Database1.qmd
         - text: "set 2"
           href: Database2.qmd
         - text: "Citations"
           href: Citations.qmd
format:
  html:
    theme:
      - morph
    css: styles.css
    toc: true
    page-layout: full


