---
title: "Videos Doodles"
format: html
---

:::: {.content-visible when-format="html"}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/7wf7NTTnSbWVkvDChqKFup?utm_source=generator" width="100%" height="100" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
::::
<span style="background-color: yellow; font-weight: bold;">^^^listen to Icon - Jaden Smith to hear this sampled!</span>

This is a collection of short video projects which I've directed, edited, and/or produced for class or extracurriculars, or just for fun! They're all pretty low-pressure projects, so don't judge any peculiar creative decisions! Many of these were completed for my Media Sketchbook class, so they're the equivalent of doodles in a digital sketchbook.

### Revolution

```{=html}

<div style="text-align: center;">
    <iframe width="640" height="360" 
      src="https://www.youtube.com/embed/lmcwEQ2HPzQ" 
      frameborder="0" 
      allowfullscreen>
    </iframe>
  </div>

```

### Frankenstime

```{=html}

<div style="text-align: center;">
    <iframe width="640" height="360" 
      src="https://www.youtube.com/embed/uRhpzbltiWQ" 
      frameborder="0" 
      allowfullscreen>
    </iframe>
  </div>

```

### Watch This Drive

```{=html}

 <div style="text-align: center;">
    <iframe width="640" height="360" 
      src="https://www.youtube.com/embed/Lqs4adoEvp4" 
      frameborder="0" 
      allowfullscreen>
    </iframe>
  </div>

```

### Yosemite

```{=html}

<div style="text-align: center;">
    <iframe width="640" height="360" 
      src="https://www.youtube.com/embed/879q3DxjQzg" 
      frameborder="0" 
      allowfullscreen>
    </iframe>
  </div>

```

### Dream Girls 

```{=html}

<div style="text-align: center;">
    <iframe width="640" height="360" 
      src="https://www.youtube.com/embed/LvAVBv2rivE" 
      frameborder="0" 
      allowfullscreen>
    </iframe>
  </div>

```

### Outside

```{=html}

 <div style="text-align: center;">
    <iframe width="640" height="360" 
      src="https://www.youtube.com/embed/R5AZzEIu_Qc" 
      frameborder="0" 
      allowfullscreen>
    </iframe>
  </div>
```

### Paranormal Inactivity

```{=html}

  <div style="text-align: center;">
    <iframe width="640" height="360" 
      src="https://www.youtube.com/embed/3JOYJG4ZZQk" 
      frameborder="0" 
      allowfullscreen>
    </iframe>
  </div>

```

### bleeeppp

```{=html}

 <div style="text-align: center;">
    <iframe width="640" height="360" 
      src="https://www.youtube.com/embed/ObJoUZgyIUY" 
      frameborder="0" 
      allowfullscreen>
    </iframe>
  </div>

```



## Longer Projects

### Halloweekend in Claremont

This short documentary gives a brief, intimate peek into the parties thrown throughout Halloweekend 2024 (Oct 31 - Nov 2). Examining music, design, communication pipelines, and administrative changes at Pomona since the 90’s, we designed this project to include the documentary below and a complementary ethnographic research paper.

[click here to watch](https://jazzminpearlduncan.github.io/Website-Project/multi/Halloweekend.html)

### Happy Everyday 

```{=html}

<div style="text-align: center;">
    <iframe width="640" height="360" 
      src="https://www.youtube.com/embed/GtU0t7yJdcg" 
      frameborder="0" 
      allowfullscreen>
    </iframe>
  </div>

```
