---
title: "Concert Attendance Project"
format: html
---

# Learning the Data

## Loading files and reading the data

```{r, message=FALSE}
# Load libraries
library(tidyverse)
library(lubridate)
library(readr)


# Read csv files containing the attendance data
all_years_files <- 
  # rules for how to search the folder
  list.files(
    path = "MDSDATA",
    # see: regular expressions
    pattern = ".csv$" ,
    full.names = TRUE
  )

all_years_data <- setNames(
  lapply(all_years_files, read_csv),
  basename(all_years_files))

head(all_years_data, 4)
```

## Cleaning the Data

### 2008-2009

```{r}

# Fall
F_2008 <- all_years_data[["2008Fall.csv"]] |>
  mutate(Date = 
           Date |>
           str_remove("\\.") |>
           str_replace("$", " 2008") |>
           mdy())

# Spring
S_2008 <- all_years_data[["2009Spring.csv"]] |>
  mutate(Date = 
           Date |>
           str_remove("\\.") |>
           str_replace("$", " 2009") |>
           mdy())


F_2008
S_2008

```

### 2010-2011

```{r}


```

### 2011-2012

```{r}


```

### 2012-2013

```{r}


```

### 2013-2014

```{r}


```

### 2011-2012

```{r}


```