---
title: "Project 5: SQL"
format: html
---

# Introduction
## Project Description
I plan to analyze the patterns and outcomes of arrests in across cities to better understand their law enforcement dynamics and the populations most affected. By examining the frequency of arrests over time and the context surrounding them—such as location, age range, and outcomes—I'll focus on trends or events that reflect how policing operates in this area. This reveals not only which groups are most frequently stopped or arrested, but also provides insight into broader social and structural patterns that shape public safety and surveillance.

The code and tables below explore how policing and traffic stops differ by location and who is most affected (within pretty specific yet broad age or location demographics). The New Orleans table shows where young people (ages 10 to 25) were most often stopped, with Bourbon Street appearing frequently—likely due to its party-heavy reputation. It’s also striking that some of the youngest people stopped were as young as 10, raising concerns about who’s being policed and why.

In the San Francisco and San Antonio comparison, we see how often arrests happened on the same calendar dates, offering a way to think about enforcement levels or patterns in each city.  This might reflect stricter policies, more dense traffic, or other local factors. On the other hand, similar arrest numbers on the same dates could hint at outside influences like holidays or big events.

Altogether, these tables help us start asking deeper questions about how place, age, and policy shape people’s (and cities') relationships with law enforcement.

## Data 

```{r}
library(DBI)
library(RMariaDB)

# connecting to database
con_traffic <- DBI::dbConnect(
  RMariaDB::MariaDB(),
  dbname = "traffic",
  host = Sys.getenv("TRAFFIC_HOST"),
  user = Sys.getenv("TRAFFIC_USER"),
  password = Sys.getenv("TRAFFIC_PWD")
)
```

All data was collected by an "interdisciplinary team of researchers and journalists at Stanford University" for  The [Stanford Open Policing Project](https://openpolicing.stanford.edu/). "[They] are committed to combining the academic rigor of statistical analysis with the explanatory power of data journalism." In this project, they've collected data from 88 cities throughout America.


# Analysis
## Table 1
### New Orleans: Stops by Location (with Average Ages)
[see dataset here](https://openpolicing.stanford.edu/data/)

This table displays the traffic stop locations in New Orleans (Dec 2009 - Jul 2018) for people between 10 and 25 years old; the average age of all those stopped at a particular location are visible, as well as the age of the youngest traffic stop target. 

It shows the average age of those stopped at each location, as well as the age of the youngest person stopped. It's striking (and somewhat humorous) to see that different locations along Bourbon Street make up the top three stop locations—likely due to its reputation as a party hub, especially during holidays like Mardi Gras. It is more concerning and interesting to see the youngest_stop column, it's interesting to see just how young the stops get (minimum was 10 yo.) and it would be interesting to also see the outcomes (citation, warning, arrest, etc.) of the youngest stops in each location. 

We can see that the table contains ages all throughout the specified age range (10-25), and the average stop age tends to hover between 18-21, which could be useful when considering the lives of young adults in NOLA, whether in the context of police surveillance or individual behavior. Further, this observation could suggest, unsurprisingly, that those that are slightly earlier in adulthood are more likely to encounter the police. 

```{sql, connection=con_traffic}
# WHERE, GROUP BY, HAVING, ORDER BY

SELECT 
  location,
  COUNT(*) AS num_stops,
  AVG(subject_age) AS avg_age,
  MIN(subject_age) AS youngest_stop
FROM la_new_orleans_2020_04_01
WHERE subject_age BETWEEN 10 AND 25 AND location IS NOT NULL
GROUP BY location
HAVING num_stops > 5
ORDER BY num_stops DESC

```
    

## Table 2
### San Francisco vs. San Antonio: How do arrests compare day-by day?
[see dataset here](https://openpolicing.stanford.edu/data/)

This table allows us to compare the number of arrests made on matching stop dates in San Francisco and San Antonio. By displaying the total number of arrests per day (if said date is in both datasets) for each city, it provides insight into differences or similarities in policing patterns, traffic enforcement intensity, or external factors influencing police activity. 

For instance, San Francisco consistently shows higher arrest counts, despite its population (909k) being smaller than San Antonios (1.3m); this could reflect stricter enforcement, denser traffic, etc. Conversely, similar arrest levels on certain days might point to shared factors like weekends, holidays, or major events affecting both cities. However, since the datasets come from different years, any comparison assumes that dates align meaningfully, which may not always hold true—so interpretations should be made cautiously. Overall, this table serves as a useful tool for identifying trends, anomalies, or behavioral patterns in traffic enforcement across different urban contexts.

```{sql, connection=con_traffic}
# JOIN, WHERE, GROUP BY, ORDER BY

SELECT 
  sf.date AS date_of_stop,
  sf.sf_arrests,
  sa.sa_arrests
FROM (
  SELECT date, COUNT(*) AS sf_arrests
  FROM ca_san_francisco_2020_04_01
  WHERE arrest_made = 1
  GROUP BY date
) sf
JOIN (
  SELECT date, COUNT(*) AS sa_arrests
  FROM tx_san_antonio_2023_01_26
  WHERE arrest_made = 1
  GROUP BY date
) sa
ON sf.date = sa.date
ORDER BY date_of_stop;




```