---
format: html
---

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/17CicZDKMQxTyo6wXS02Xz?utm_source=generator" width="100%" height="100" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

### About Me

My name is Jazzmin, or Jazz, and I am currently a Senior at Pomona College studying Media Studies and Data Science, with a concentration in Electronic Media Production. I've bounced around several different interest areas -- including (but not limited to) AI, Intellectual Property Law, DJing, and News Writing. 

Data transfers, radio signals, news casts, remixed tracks; it's all information that's been diced up to appeal to or be understood by different subjects. This concept, that everything we process (including media) is just re-purposed data, is not new; however, it has underpinned my extracurricular and professional pursuits.

I love to experiment with boundary-stressing avenues of expression through data and culture, particularly through writing, music, and video editing. Chopping and screwing visual, sonic, numerical, textual, and historical data, I aim to broach the worlds of entertainment journalists, marketing professionals, creative directors, and talent managers; bridging my creative ability to craft complex narratives with my passions for arts and entertainment through high-impact, culturally relevant, collaborative projects. 

### About My Work

I have been writing as a journalist for 7 years; producing audio-visual content (documentary film, infographics, fan-edits, music, etc.) for 4 years; and managing several coinciding cross-disciplinary projects for 3 years. From [The Knight Times Newspaper](https://jazzminpearlduncan.github.io/Website-Project/nonfiction.html#articles-and-journalism) to [The Post Newspaper of Galveston County](https://jazzminpearlduncan.github.io/Website-Project/nonfiction.html#articles-and-journalism) to [The Feedbacker](https://jazzminpearlduncan.github.io/Website-Project/nonfiction.html#articles-and-journalism), I've maintained a pointed interest in pop-culture developments and entertainment news, varying between print and visual media as mediums for storytelling through my reporting. Starting Circuits, Internet, Media, + Software (CIMS), my on-campus production organization, has been my boldest step in embracing this vision of a multi-media, interdisciplinary work environment. 

Publishing [The Loop](https://jazzminpearlduncan.github.io/Website-Project/TheLoop.html) -- a Zine collection dedicated to dignifying and platforming student artwork, writing, software, and interactive media projects -- under CIMS, as well as maintaining scheduled community engagement and education events, is one of my proudest achievements, skill- and concept-wise; one that I am looking forward to expanding upon professionally. Bringing fandom communities and underground niches to the forefront of the 5C community through DJ sets, social media campaigns, and production projects, I have developed a knack for developing, following, and platforming marginalized voices through my creations.

Embracing music, film, and writing as chosen mediums, I am looking to pursue a career in entertainment journalism, design, music A&R, or creative content development where I can continue to hold my hand to the pulse of pop-culture, challenge arbitrary boundaries, advocate for underrepresented voices, platform important conversations, and investigate how people and information interact with one another.


